-- AlterEnum
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'MEDIA_MANAGER';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'PROCUREMENT';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'HR';
ALTER TYPE "RoleType" ADD VALUE IF NOT EXISTS 'AUDITOR';
